@file:Suppress("UnstableApiUsage")
@file:OptIn(ExperimentalPathApi::class)

import buildsrc.utils.toCamelCase
import kotlin.io.path.ExperimentalPathApi
import kotlin.io.path.createDirectories
import kotlin.io.path.deleteRecursively
import kotlin.io.path.writeText
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi

plugins {
  id("buildsrc.conventions.kotlin-gradle-plugin")
}

description = "Settings plugin that makes Kotlin DSL delegated accessors available to every build script."

dependencies {
  implementation(project(":modules:accessors"))
  api(project(":modules:accessors-root"))
}

gradlePlugin {
  plugins {
    create("gradleKotlinAccessors") {
      id = "dev.adamko.gradle-kotlin-accessors"
      implementationClass = "dev.adamko.gradle.kotlinaccessors.AccessorsSettingsPlugin"
      displayName = "Gradle Kotlin DSL Accessors"
      description = "Makes Kotlin DSL delegated accessors available to every build script."
    }
  }
}

val generateGkaVersionKt by tasks.registering {
  val outputDir = temporaryDir.toPath()
  outputs.dir(outputDir)

  val projectVersion = provider { project.version.toString() }
  inputs.property("version", projectVersion)

  val projectGroup = provider { project.group.toString() }
  inputs.property("projectGroup", projectGroup)

  val projectsIds = objects.setProperty<Pair<String?, String>>()
  projectsIds.convention(
    provider {
      setOf(
        projects.modules.accessors,
        projects.modules.accessorsCore,
        projects.modules.accessorsDsl,
        projects.modules.accessorsRoot,
        projects.modules.settingsPlugin,
      ).map { it.group to it.name }
    }
  )
  inputs.property("projectsIds", projectsIds)

  doLast {
    val projectsIds = projectsIds.get()
      .map { (group, name) ->
        requireNotNull(group) { "$name has null group" }
        group to name
      }
    val fileContent = buildString {
      appendLine("// Do not edit: generated by $path")
      appendLine("package dev.adamko.gradle.kotlinaccessors.internal")
      appendLine()
      appendLine("internal object GradleKotlinAccessorsBuildMetadata {")
      appendLine()
      appendLine("  const val version = \"${projectVersion.get()}\"")
      appendLine()
      appendLine("  const val group = \"${projectGroup.get()}\"")
      appendLine()
      appendLine("  data class Module(")
      appendLine("    val group: String = GradleKotlinAccessorsBuildMetadata.group,")
      appendLine("    val artifact: String,")
      appendLine("  ) {")
      appendLine($$"""    val coordinate: String = "$group:$artifact"""")
      appendLine()
      appendLine("    companion object {")
      projectsIds.forEach { (group, name) ->
        if (group != projectGroup.get()) {
          appendLine("      val ${name.toCamelCase()} = Module(group = \"$group\", artifact = \"$name\")")
        } else {
          appendLine("      val ${name.toCamelCase()} = Module(artifact = \"$name\")")
        }
      }
      appendLine()
      appendLine("      val entries: Set<Module> =")
      appendLine("        setOf(")
      projectsIds.forEach { (group, name) ->
        appendLine("          ${name.toCamelCase()},")
      }
      appendLine("        )")
      appendLine("    }")
      appendLine("  }")
      appendLine("}")
    }

    outputDir
      .resolve("dev/adamko/gradle/kotlinaccessors/internal")
      .apply { deleteRecursively() }
      .createDirectories()
      .resolve("GradleKotlinAccessorsBuildMetadata.kt")
      .writeText(fileContent)
  }
}

kotlin.sourceSets.main {
  @OptIn(ExperimentalKotlinGradlePluginApi::class)
  generatedKotlin.srcDir(generateGkaVersionKt)
}
